title: Harrison Sneddon # your name (or website title) here
logo: "/images/HTS_LKDIN.jpg" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Investment Banking Analyst - Industrials and Integrated Technology
  <br>
  
  <br>
  Lehigh University
  <br>
  B.S in Business and Economics - Finance Concentration
  <br><br>
  <a href="https://linkedin.com/in/harrison-sneddon/">LinkedIn</a> 
  <br>
  <a href="HTS CV.pdf" class="btn btn--info">Resume</a>   
  <br>
  <a href="CONTACT.md">Contact</a> 
  <br>
  <a href="https://www.raymondjames.com/corporations-and-institutions/investment-banking">Raymond James</a>  
  <br>

  
theme: jekyll-theme-minimal
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one